name: Publish PyPI Package & Docker

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install build dependencies
        run: |
          sudo apt install libx11-dev libxcursor-dev libpng-dev
        continue-on-error: false

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        continue-on-error: false

      - name: Building
        run: |
          python setup.py install sdist bdist_wheel
        continue-on-error: false

      - name: Testing
        run: python -m unittest
        continue-on-error: false

      - name: Publish to Registry
        uses: HurricanKai/Publish-Docker-Github-Action@master
        if: contains(github.ref, 'refs/tags/v')
        with:
          name: clickgen
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          cache: true
          tagging: true
          snapshot: true
          dockerfile: Dockerfile
        continue-on-error: false

      - name: Publishing to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine --version
          twine upload dist/*

      - uses: actions/upload-artifact@master
        if: success()
        with:
          name: dist
          path: dist

      - uses: actions/upload-artifact@master
        if: success()
        with:
          name: xcursorgen
          path: ./clickgen/xcursorgen.so
