name: Publish on PyPI

on:
  release:
    types: [created]

jobs:
  build-n-deploy:
    if: "github.event.release.released"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install build dependencies
        run: |
          sudo apt install libx11-dev libxcursor-dev libpng-dev
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py install
          python setup.py sdist bdist_wheel
          twine upload dist/*
